travis:
  secure:
    BINSTAR_TOKEN: suFfec8uy+3b4t54vsPszPTWb55lvHuQHmNy+K0mylOUqp9J/TE6Bs9hecFWoXqPuoYgW5nVfKmssjp5ewm58/hwtp1FyFPC3YJmSN6owpwhb493XZmZ32IhgIvWEap2IdkkGRNiktDAkVlWgmdf8JNvgsTyktRqZaN43KjnWGHFsIVNqS+dST06n9Hsph02j7FDiFSzbEKufj+ATgZyEi0Bms4milAAqvWywJIXSdrKvN8MK5oYHlUXqSfNyhnDE097Em8vccw3VETzX6Yk9eMECN+x58+Mi5x9u5CaUsrbDn0LvkuUvl1R3OVXEY0hnnVnZiGpe5Df/+qPw1BTqz0trFosPiXvjwDXeU+3eKlWZZ3899AWBzdfxTxwFXOBrx1CCyU0E/kHWYIQ1kDrqi1/0gKJVuP+lAla87DFqVNhPBsfpEMAtX/hj7myy6a15+Ac1ObfDsxlwKPonT4zdt7PvrW5xpQcUbcNZehFQgkxzbsSQZdSGfUlTQG6mSBshaSHxFyIFsdGJQISbzhQv0nVjb+ytrYRYQ3Ahv/ziEDjvkstkGY0JbtLk/fFqP29LrMGYinWEUWCNWuOsb5XmRRcRnCNJUhLdlhneOmVwvcOr0XZ6koA3jstMPGgyB29KC2+R99XWKt/3aV7i0QFX2VuFHuzi/P8PrPSLS/aNa8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
