travis:
  secure:
    BINSTAR_TOKEN: JGyZlquahK34Ez8KrOViN9JufP2zO6441TJXFpEc7hNyCBC4b/OBkvNssP0sNxd5nZqa04T+tTUO4j8tAuvu8uyv49jjXgNR63O+z0EuWhsDRT40jR441vOcmIbZs7PoxUMEdoq7xRmYzg1vSQ02zjWCgFy/e1cMPlsgJtoRGIl0xCq19RVifFPK9oRvWhEs+tnj24Tq+gSPnt88XhT4gVIwjexyyjdc7/ZU1BD7LzQk1LGFwLYX0OCDZaUPc4X8s+CvJm39Xrv3auYdn+omFLrCAIEpMpYnAJr/PYUDXuYsdBto5JhBjraFhcrVkmw7jManks4DquCBmOYDw5UgxBQc4c7U4DgV5fJbeSxw4Srj2HwITTtWuqsN9MeE6LU7fCIEOeV0Vs+gAvLC9qiB2f3fGCqUNoeKSdILZ1M5U0tDG3fUQwbpvFJrkvI7QQYeOiwMPW9VGJePREGBFlsyCxl266vlbkqGwhjg80KvShxXGBuasINrlVHUF10e+9GP4UwsCGYqQgilCGYQaM+j1iTBNhcFwMAoW4NRzDN5Iik9k3BsdoiI+9ErHyQ8rR27H8lRTWya4vWrUFcMy1u49hA8gqsL7hzGT2WB+VOR6Q6O5eLxiOqK7gA6LN3i9QuigENi4kYn3qih3l4V7YJLaoQbG8BDswn5FBvnDZdjLQY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
