appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: npIe75lLUuPPSivnlrwE8ZnOOLPaYaKJMsuA2oYxJAOKPvI/Avh9jsotGRwstZd07FOD53BQ2jpbsSn29f9f2A/ABg8lpKNnF9FPLlPpXZ+4eWGKqJJ7tZDbknrt5ndJppGC13tVmrWQpXIpdn4HbSNnzV1yxd2+TJZupdysV5unBAGEoA6ji6ytr8UQ1mRAWT6VYZbMjHAX82EQAGIRUbYmqhgNbLEKdaxWaqOiM1tttFj9pkrgUfztorBIp6xvqJ6TgWM71rxVSfY3bUq8k67gwzIKKt5iMviaU7N5MWRL2cwjggUmwibiLAnKn0DxIZeya6uQ3CPdF5Y6Wf+rYYCqd0mO5vof1ALAiwRxrPtdcDTjlCXFk3V89C4MT57/Mg7o4FkAPfkEfLa1xFTK4X3+8xujVtmfmuV7Lb6qVV+hLe7akQMoJ7+p9VSYBB24mEolChupusv9JCZdRbi6riE0GY1y3l96mTHKWiqPC7JYw9Hd5mPZrmK9nVAozwJpq+wfxXWy9fcDhxn7R14ymMyiKrKORD3GUfIqvDI5xiQsFD9ekMOx94ig3wpTt/7zgqjkX281WFtK2tkLNR3YVaZ4YMH+rQqkcSq+QMSsSJPRxqRRMB0jI5czjoEBgPQqTEP+420PEO1ATvheXLGk5t0zySKHCkCU4uFz5JpOZZI=
