travis:
  secure:
    BINSTAR_TOKEN: xD+yQ3dc0TtbPdWZnceKTfWMt643IUeo0oGY2+qUt5KzmzHn2sAsvRRt6QBZln8cyYlMtHIEO5B8lR16DjQeSHEDNK2P2FJ2eFF3tKLKFnwu2vgiz1Ocq+s3X1d7vWvqG57RqlKInD5gwyngcX29Hvf2VUwGR4695nqQD22Bvj5TRsP2hto25ucYdHbQuyIXSnXc50aUxwf/EqkeaK3546JRZ0H9Yipe5wyXcNrDbCncYmFs4oTD6eLpWV8laq90EyXLXpxkuUj/mdbhBOwZ5Y4MTCoM8r6XJo5yu5G9ohx+Ua1I6FWJv7ssf6V/wJr4LwrNSLYFTjl+HuUxewkPWIggYsaGOf+Shztygs5Rc/a/yUOWilnV/jpvnOXPBa3LQLd49LhwYlkFzhPKbMWtXSCLoIvvO74ExGZhw2Z7SYaDqL2FV1eUeg3UTdNUsyIxK5kwuheh4bszs5PXkQBCpszw0y42YePebAg7nTwwF9t3AwhAkhygy+Nb+Rn17cxWpc2jQ2hNYZeleW+rd9M9HU8AlKgV6zS+F51YV9A5PLP/LRX9w7gMQQHg1hATpZsjN3dDKk57C2mAtXkRS/predFNjE/0NztsjSWURPh7G0ddBpRhIs2RRy4aUsswsnAUFR6I5cNOtJ94qc24XJTu5XzL5CCIJuwI2d1gwLWHHGk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
